[serve]
# Explicitly bind to localhost only to prevent serving on random hosts
addresses = ["127.0.0.1"]
port = 5000
# Disable address lookup to prevent trunk from trying multiple addresses
disable_address_lookup = true
